language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: cnheider
  password:
    secure: kTWGPQ7k8WpPOxwlKVMeyOoxoZCFpxfLmF/ebq9ocWS3IdkKe/ngz5DaksNzax/fpEqiFPrY/Qf1D+aV1Esc9kVvtov6eMGkAArCou+IWtT5FR7snTPRt+zxS+R8bQ2C8Ncytq9P6CvM5E+zHkqrJU+oovAtobnLZp7z/8vrWKIms6hP61MC43UFocmplKGkHhQX0m2LoXD5qQk4sIB/RyggVisAUk+G7kCMUcIpu1M3hAkwaBPiQkAViaK4RCJPllD4JKYq9idfOtiScFY/mZJA8QJ1fypOMTuzhNi03rj0FwW52f9FbScWn5HH4aFupeaK0kBbDo9D7XQgoGGYSzpKe32ehex/brJZoC1KnOrhFhw/B2jhjyUCYLb6IENzggBQKGQKLZpcTxeNEDXcVe7S2IQuu08uMkCgusbyW1IEpy+Saut9doKfyPa0tzPA3E85WcbCFnAbkjoDLtTbidKnCX4HmH3HULhThWVuRGccvN5JlGW+tknzsNeZVrAn4p+uuP9vepkgTrwcBgZyB1U0WqkEsj3yO5foNRNZ4z8l4lyvFx+TeIAbSZgpNlZPWO3mh28qfWefkZj4FJ9V6c2fPrLhxYF7WsUDf3JR9UUAE8AEMWu2q3AWj9/uJy7myI4DK/kQwXq5NWEnTLiUGeMlukJMVRLqchOaHf6eio8=
