dist: xenial
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install -e .
script:
- pytest --cov=warg --ignore=tests/test_toaster.py
- coveralls
- black --check warg
deploy:
  provider: pypi
  user: aivclab
  password:
    secure: Xjo9A3DPqGg8nSCn7XCyNct/rJQOb68v6Ii9f9QokYuK1w975e/yyN9Z+WvDUW1w5tC105TjKKjPFrg5DXTIk3nXRY6f81AwjeAhDnO3Fb6I9fpK4zb2cprGmykVvly1yVvMpP6w3TxshP3I7Mx5dLArw9ZC7AsGNm5eTF1NZ84bB6Bvs0U7e1CFmbBI+mWeH1jLELDT9MGI37AwSx5I94QOH/eghBIAlIUhOuorYA2eaPO5H7lRXYOqZOcob/BwHNWIsQaVp+9LZygz0cYXWEL6O/j4WEqpIdik9F+S8CHXYgFNqGIkECp8Wq8dwfSqOdmKx+Jq+ibkIGw4hqqP2ddItU09pLLpFlwXJmih27/VhXrGb5fBHyT4GsKthWN+AM6bLt/bd97YUD714+kmBkmGnUsC8bOQGBEdX3gHwEv70yIjWqZk8lIb4fkBZOcJ1EJYa/FhPDpTa+oFvL3ZvAjUX9uO83LZnAiaoBy+X7vmRVuB2HAH8IzErFP8n80M2PM6M6bKvCmMaDCD25BIFx4b4yshhDzIicwmUqFc5Sr2ptVw9A0O8xufXAqDM22aqZPChhCmt+7W/kLN8KQlHB4Dfcl2nw4WJLnLJhYP//OaZagIX3aq2E4UOlvTo+qK+pyhznitkrY5MlGwBUvGm8f1G0kzr6EI4pTgPd8ivxs=
  on:
    tags: true
